import type { Md3Role, Md3TokenSet, Md3Tokens } from './md3.ts'

function cssVarName(role: Md3Role): string {
  return `--md-${role.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}`
}

function renderBlock(selector: string, tokens: Md3Tokens): string {
  const lines = Object.entries(tokens).map(([role, hex]) => `  ${cssVarName(role as Md3Role)}: ${hex};`)
  return `${selector} {\n${lines.join('\n')}\n}`
}

/**
 * Renders the MD3 token set as plain CSS custom properties — deliberately *not*
 * pre-resolved into rgb()/color-mix() strings here. The Uno color rule (see
 * uno-preset.ts) is what adds transparency support on top of these variables.
 */
export function renderMd3CssVariables(tokens: Md3TokenSet): string {
  return [
    '/* Generated by packages/design-system/scripts/generate-tokens-css.ts — do not edit by hand. */',
    renderBlock(':root', tokens.light),
    renderBlock(':root[data-theme="dark"]', tokens.dark),
    '@media (prefers-color-scheme: dark) {',
    '  :root:not([data-theme="light"]) {',
    Object.entries(tokens.dark)
      .map(([role, hex]) => `    ${cssVarName(role as Md3Role)}: ${hex};`)
      .join('\n'),
    '  }',
    '}',
    ''
  ].join('\n')
}
