#!/usr/bin/env bash
# import-kanban.sh — regenerate foam/features/shipped.md and backlog.md from GitHub issues.
#
# Requires: gh, jq. Run from a git repo with GitHub remote.
#
# Usage:
#   ./import-kanban.sh [--dry-run] [--limit N] [TARGET_DIR]
#
# Does not create ADRs or PRDs — only issue indexes for the feature catalog.
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DRY=0
LIMIT=500
TARGET=""

log() { printf '%s\n' "$*"; }
die() { printf 'import-kanban: %s\n' "$*" >&2; exit 1; }

usage() {
  sed -n '2,10p' "$0"
  exit 0
}

resolve_target() {
  if [ -n "$TARGET" ]; then
    cd "$TARGET" || die "cannot cd to $TARGET"
  fi
  if git rev-parse --show-toplevel >/dev/null 2>&1; then
    cd "$(git rev-parse --show-toplevel)"
  fi
  pwd
}

gh_repo_slug() {
  gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null \
    || die "not a GitHub repo or gh not authenticated"
}

write_file() {
  local path="$1"
  local content="$2"
  if [ "$DRY" = 1 ]; then
    log "DRY  write $path ($(printf '%s' "$content" | wc -l) lines)"
    return
  fi
  mkdir -p "$(dirname "$path")"
  printf '%s' "$content" > "$path"
  log "write $path"
}

main() {
  while [ $# -gt 0 ]; do
    case "$1" in
      --dry-run) DRY=1;;
      --limit) LIMIT="$2"; shift;;
      -h|--help) usage;;
      -*) die "unknown option: $1";;
      *) TARGET="$1";;
    esac
    shift
  done

  command -v gh >/dev/null 2>&1 || die "missing: gh"
  command -v jq >/dev/null 2>&1 || die "missing: jq"

  REPO_ROOT="$(resolve_target)"
  FOAM_FEATURES="$REPO_ROOT/foam/features"
  [ -d "$REPO_ROOT/foam" ] || die "foam/ not found — run init.sh first"

  SLUG="$(gh_repo_slug)"
  GENERATED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  log "repo : $SLUG"
  log "root : $REPO_ROOT"
  log ""

  ISSUES_JSON="$(gh issue list --state all --limit "$LIMIT" \
    --json number,title,state,labels,closedAt 2>/dev/null)" \
    || die "gh issue list failed"

  COUNT="$(printf '%s' "$ISSUES_JSON" | jq 'length')"
  log "issues: $COUNT (limit $LIMIT)"

  # --- shipped.md ---
  SHIPPED="# Shipped features

#product

_Auto-generated by foam-project-memory \`import-kanban.sh\` at $GENERATED._
_Source: [$SLUG](https://github.com/$SLUG/issues). Regenerate after releases; distill
important items into PRDs and ADRs manually._

## Closed issues

| Issue | Title |
| ----- | ----- |
"

  while IFS=$'\t' read -r num title; do
  [ -n "$num" ] || continue
  SHIPPED="${SHIPPED}| [#${num}](https://github.com/${SLUG}/issues/${num}) | ${title} |
"
  done < <(printf '%s' "$ISSUES_JSON" | jq -r '
    [.[] | select(.state == "CLOSED")] | sort_by(.number) |
    .[] | "\(.number)\t\(.title | gsub("\n"; " ") | gsub("\\|"; "/"))"
  ')

  SHIPPED="${SHIPPED}
## Documented as PRD / ADR

Link substantial features to \`prd/\` and \`foam/decisions/\` — not every closed
issue needs an ADR.
"

  # --- backlog.md ---
  BACKLOG="# Backlog & upcoming work

#product

_Auto-generated by foam-project-memory \`import-kanban.sh\` at $GENERATED._

## Open issues

| Issue | State | Title |
| ----- | ----- | ----- |
"

  while IFS=$'\t' read -r num state title; do
  [ -n "$num" ] || continue
  BACKLOG="${BACKLOG}| [#${num}](https://github.com/${SLUG}/issues/${num}) | ${state} | ${title} |
"
  done < <(printf '%s' "$ISSUES_JSON" | jq -r '
    [.[] | select(.state == "OPEN")] | sort_by(.number) |
    .[] | "\(.number)\t\(.state)\t\(.title | gsub("\n"; " ") | gsub("\\|"; "/"))"
  ')

  BACKLOG="${BACKLOG}
## Epics (link PRDs when scoped)

| Issue | PRD |
| ----- | --- |
| _(add rows when PRDs exist under prd/)_ | |

## Next steps for agents

1. Pick an open issue from the table above.
2. If non-trivial, create \`prd/PRD-NNN-slug.md\` and \`plans/PLAN-NNN-slug.md\`.
3. Record new architecture choices in \`foam/decisions/\`.
"

  write_file "$FOAM_FEATURES/shipped.md" "$SHIPPED"
  write_file "$FOAM_FEATURES/backlog.md" "$BACKLOG"

  log ""
  log "done. Review foam/features/ and distill epics into PRDs/ADRs."
}

main "$@"
